feat(intellij): enable jumping to target & configuration from toolwindow
nrwl/nx-console pull request #1736
Opened 2023-05-17 12:14 UTC by MaxKless

- identify configuration nodes
- produce correct run configuration
- start
- implementation

2023-05-17 20:01 UTC, Cammisuli submitted a review, later dismissed
Just revert the color changes in the vscode settings, and it should be good to go

2023-05-17 20:01 UTC, Cammisuli commented on .vscode/settings.json
> +  "peacock.color": "#215732"
revert this

2023-05-17 20:02 UTC, Cammisuli requested changes
see previous comment

2023-05-19 08:07 UTC, MaxKless commented on .vscode/settings.json
> +  "peacock.color": "#215732"
oops, reverted

2023-05-19 13:06 UTC, merged