feat(vscode): Sort target names alphabetically
nrwl/nx-console pull request #1963
Opened 2023-12-14 13:37 UTC by pietdevries94

Implements #1959 
I checked if it works with run target and in the nx panel. Both are sorted alphabetically.

2023-12-20 16:50 UTC, MaxKless commented
Sorry for the slow communication. This looks good, I'll have a look at it soon to see if there's anything we missed.
Appreciate the PR a lot!!

2024-01-02 11:26 UTC, MaxKless requested changes
one sort is missing, otherwise it looks good. 

For the project view, I would not sort the projects for now. Since the project view is kind of a visualisation of project.json files, it makes sense to keep the same order.

But for the run target view & quickpicks, it's a good idea. So just one small change.

Do you have access to IntelliJ? Because we'll need to implement the changes there too.

2024-01-02 11:26 UTC, MaxKless commented on libs/vscode/nx-cli-quickpicks/src/lib/select-run-information.ts
also sort in the other if condition:

```
if (projectName) {
    return Object.keys(workspace.projects[projectName].targets || {}).sort();
  }
  ```

2024-01-03 15:59 UTC, pietdevries94 commented
I did the two changes as requested :) 

I sadly don't have an IntelliJ setup and I also haven't written any Java for like 15 years, so I don't feel as comfortable to make the same change at that side.

I however have enabled edits on this PR so if you want to do it, feel free to add it here. And if someone else wants to do it, feel free to ask, I'm fine with inviting people on that repo

2024-01-22 14:31 UTC, merged