feat(vscode): add nxWorkspacePath configuration option
nrwl/nx-console pull request #2274
Opened 2024-10-01 05:31 UTC by gabynevada

This pull request introduces a new configuration option for specifying the Nx workspace path in the VSCode extension. It includes updates to the configuration schema, the main application logic, and the configuration keys.

### Configuration Updates:

* [`apps/vscode/package.json`](diffhunk://#diff-ffd752c4d60ebba40a59cc7f9b8cb7b3beeedb5c14a8a8245246bf73846bf247R709-R712): Added a new configuration option `nxConsole.nxWorkspacePath` to specify the relative path to the root directory of the Nx workspace.
* [`libs/vscode/configuration/src/lib/configuration-keys.ts`](diffhunk://#diff-3decce50608b8a2ee224694c2ee734de8fcb9869a49067d0635d9ffbaaa425ffR15): Added `nxWorkspacePath` to the `GLOBAL_CONFIG_KEYS` array and updated the `GlobalConfig` type to include this new configuration key. [[1]](diffhunk://#diff-3decce50608b8a2ee224694c2ee734de8fcb9869a49067d0635d9ffbaaa425ffR15) [[2]](diffhunk://#diff-3decce50608b8a2ee224694c2ee734de8fcb9869a49067d0635d9ffbaaa425ffR32)

### Application Logic Updates:

* [`apps/vscode/src/main.ts`](diffhunk://#diff-c33c47bb60ec17445029914b7d1e16edb9670d787c2d4deb020b813d1f9be946L2-R2): Imported the `resolve` function from the `path` module.
* [`apps/vscode/src/main.ts`](diffhunk://#diff-c33c47bb60ec17445029914b7d1e16edb9670d787c2d4deb020b813d1f9be946R151-R162): Modified the `scanForWorkspace` function to use the new `nxWorkspacePath` configuration setting to determine the current directory.

2024-10-01 05:51 UTC, gabynevada commented
https://github.com/user-attachments/assets/85eefd81-7917-4036-98b4-43bbc8328409

2024-10-01 09:51 UTC, MaxKless requested changes
Nice! Wow you're fast. Thanks for this.

This is still missing some important pieces imo:
- When using the `Select Workspace` command (`nxConsole.selectWorkspaceManually`, which ends up calling the `main.ts#manuallySelectWorkspaceDefinition` function), the setting should be updated to contain the relative path. 
- There should be a change listener (`workspace.onDidChangeConfiguration`) so that when this setting is changed, `setWorkspace` is called and Nx Console updates automatically. That way users won't have to restart the ide
- [Make sure the configuration is workspace-level](https://code.visualstudio.com/api/references/contribution-points#contributes.configuration) (by using the scope property) so it can be shared between anyone who clones the repo. Because realistically, anyone with a nested repo will probably set this setting the same.
- The configuration description should specify that this should be a relative path and is a workspace-level setting

2024-10-01 13:34 UTC, gabynevada commented
Makes sense, thanks for the quick feedback!

> * [Make sure the configuration is workspace-level](https://code.visualstudio.com/api/references/contribution-points#contributes.configuration) (by using the scope property) so it can be shared between anyone who clones the repo. Because realistically, anyone with a nested repo will probably set this setting the same.

What scope would be the correct one for this? When I was testing, went with the window setting which works in both the workspace and user settings, and since it was the default I removed the property.

2024-10-06 22:53 UTC, gabynevada commented
@MaxKless had a busy week from work but pending tasks should be completed now. Let me know if there's any issues or additional changes.

2024-10-07 18:11 UTC, MaxKless approved these changes
Thanks, code looks great and works great!

2024-10-07 18:11 UTC, merged